apiVersion: v1
kind: Service
metadata:
  name: alamesabackendservice
spec:
  selector:
    app: alamesabackendlabel
  type: LoadBalancer
  ports: 
    - name: alamesabackendport
      port: 80
      targetPort: 8000
  externalIPs: 
    - 192.168.49.2 
