apiVersion: v1
kind: Service
metadata:
  name: alamesadatabaseservice
  labels:
    name: alamesadatabasestatefulset
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    role: mongo
